# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vois' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vois
  pod 'Firebase/Analytics', '~> 6.19.0'
  pod 'Firebase/Auth', '~> 6.19.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  target 'VoisTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
